### ISSUE TITLE
Macbook air m2 실행 오류

### ISSUE THREAD

**Issue by puppy9207** [wlxo0401/MAutoClick#1]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/26337691/219520219-70e893b3-cbc0-4273-837f-400dcb125f06.png">

다음과 같은 문제가 발생했습니다.

환경 정보
- Chip : Apple M2
- Memory : 16GB
- Disk : Macintosh HD
- macOS : Ventura 13.1

**Comment by wlxo0401** [comment]
애플 앱 인증을 통하여 해결하였습니다.

**Comment by wlxo0401** [comment]
애플 앱 인증을 통하여 해결했습니다.
