### ISSUE TITLE
I have two suggestions.

### ISSUE THREAD

**Issue by kelvinlee** [wlxo0401/MAutoClick#2]
1. The shortcut keys cannot be turned off at run time because the shortcut keys are not global now.
2. Can we give each action a separate loop? Like clicking five times before moving on to the next action.

Thanks.

**Comment by wlxo0401** [comment]
That's a great idea. I'll apply it in the next update.

**Comment by wlxo0401** [comment]
I'm busy with work so I can't seem to update quickly. Please wait a little longer.

**Comment by wlxo0401** [comment]
I'm busy with work so I can't seem to give you an update sooner. I'll leave a comment when it's updated.

**Comment by kelvinlee** [comment]
It's OK, I can wait , 😄

**Comment by wlxo0401** [comment]
1. Global hotkey function
(Only the start/stop button has been created globally. I thought it was meaningless to do other functions globally. What do you think?)

2. I repeated each action and added a delay.
(Although 'Delay Action' already exists, I thought I would have to add a delay as an action detail to get it to repeat for each action.)

3. UI Update

4. I added the code you added. And the code that fetches the saved task has been changed to a function. By any chance, please check further to see if it works as intended.

There are a lot of things that have been added and changed this time, so I want to do more tests and I have not made it with dmg yet.

To verify it, you need to build it with code and test it.

I'm very grateful for your interest.

**Comment by wlxo0401** [comment]
1. Global hotkey function
(Only the start/stop button has been created globally. I thought it was meaningless to do other functions globally. What do you think?)

2. I repeated each action and added a delay.
(Although 'Delay Action' already exists, I thought I would have to add a delay as an action detail to get it to repeat for each action.)

3. UI Update

4. I added the code you added. And the code that fetches the saved task has been changed to a function. By any chance, please check further to see if it works as intended.

There are a lot of things that have been added this time, so I think we need to proceed with more tests.

It is not yet made into a dmg file. if you want to test it, you need to build it with the latest code.

I'm very grateful for your interest.

**Comment by kelvinlee** [comment]
1. Yes, you are right.
2. It's good for easy set task.

It's my pleasure.
